apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      imagePullSecrets:
        - name: scw-regcred
      containers:
        - image: rg.fr-par.scw.cloud/namespace-yte2e/nginx:v0.1.0
          name: nginx
          ports:
            - containerPort: 3000
