resources:
  - ../../base
namespace: ydubber-dev
images:
  - name: rg.fr-par.scw.cloud/namespace-yte2e/ydubber-backend
    newTag: v0.0.16
patches:
  - target:
      group: networking.k8s.io
      version: v1
      kind: Ingress
      name: ydubber-ingress
    path: ingress-patch.yaml
  - target:
      group: bitnami.com
      version: v1alpha1
      kind: SealedSecret
      name: scw-regcred
    path: docker-secret-patch.yaml
