resources:
  - ../../base
  - docker-secret.yaml
patches:
  - target:
      group: networking.k8s.io
      version: v1
      kind: Ingress
      name: ydubber-ingress
    path: ingress-patch.yaml
namespace: ydubber-dev
